name: 'Build APBS binary'
description: 'Build APBS binary'

inputs:
  basedir:
     description: 'base dir'
     required: true

runs:
  using: "composite"
  steps:

  - name: download APBS source
    shell: bash
    run: |
      set -eux
      BASEDIR=${{ inputs.basedir }}
      mkdir -p $BASEDIR
      cd $BASEDIR
      wget --progress=dot:mega -c https://github.com/Electrostatics/apbs/archive/refs/tags/v1.5.0.tar.gz
      tar xzf v1.5.0.tar.gz


  - name: download FETK source
    shell: bash
    run: |
      set -eux
      BASEDIR=${{ inputs.basedir }}
      mkdir -p $BASEDIR
      cd $BASEDIR

      SRCDIR=$BASEDIR/apbs-1.5.0

      # FETK (0c6fdeabe8929acea7481cb1480b5706b343b7e0)
      git clone https://github.com/Electrostatics/FETK.git
      cd FETK
      git checkout 0c6fdeabe8929acea7481cb1480b5706b343b7e0
      FETK_DIR=$BASEDIR/FETK
      cd $SRCDIR/externals/fetk
      ln -s $FETK_DIR/maloc
      # ls -la
      
  - name: Build APBS
    shell: bash
    run: |
      set -eux
      BASEDIR=${{ inputs.basedir }}
      mkdir -p $BASEDIR
      cd $BASEDIR

      SRCDIR=$BASEDIR/apbs-1.5.0
      BUILDDIR=$BASEDIR/build
      INSTALL_DIR=$BASEDIR/target

      # v1.5.0
      cmake -S $SRCDIR -B $BUILDDIR \
      -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
      -DCMAKE_BUILD_TYPE=Release \
      -DAPBS_STATIC_BUILD=ON \
      -DBUILD_DOC=OFF \
      -DBUILD_TOOLS=ON \
      -DENABLE_TESTS=OFF \
      -DCMAKE_EXE_LINKER_FLAGS='-z muldefs'
      
      cd $BUILDDIR
      make -j 8
      make install

  - name: Check built binary
    shell: bash
    run: |
      BASEDIR=${{ inputs.basedir }}
      mkdir -p $BASEDIR
      cd $BASEDIR

      INSTALL_DIR=$BASEDIR/target

      bash -c "$INSTALL_DIR/bin/apbs --version; echo"

      ls -la $INSTALL_DIR
